# switch package manager based on os family

- include: "yum.yml"
  static:  yes
  when:    ansible_os_family == "CentOS"

- include: "apt.yml"
  static:  yes
  when:    ansible_os_family == "Debian"

- include: "tests.yml"
  static:  yes
  when: packages.tests is defined
