- name: remove packages if defined
  yum:
    name:  "{{ item }}"
    state: absent
  with_items:
    - "{{ packages.remove }}"
  when:
    packages.remove is defined

- name: install packages if defined
  yum:
    name:  "{{ item.name }}"
    state: "{{ item.state | default('latest')}}"
  with_items:
    - "{{ packages.install }}"
  when:
    packages.install is defined

- name: upgrade Packages
  yum:
    name:  "*"
    state: latest
  when:
    packages.upgrade is defined and
    packages.upgrade == True
