# switch package manager based on os family

- name: debug1
  debug:
    msg: "OS family is ({{ ansible_os_family }})"

- include: "yum.yml"
  static:  yes
  when:    ansible_os_family == "CentOS"


- include: "apt.yml"
  static:  yes
  when:    ansible_os_family == "Debian"
